MARKETCHECK_API_KEY = "CVQFc2TL3qrcf18ssvi9Mz78rOEjrGI2"

API_URL = "https://dealer-backend-render.onrender.com"


[theme]
base="dark"
primaryColor="#3B82F6"
backgroundColor="#0F172A"
secondaryBackgroundColor="#1E293B"
textColor="#E5E7EB"
font="sans serif"
