MARKETCHECK_API_KEY = "CVQFc2TL3qrcf18ssvi9Mz78rOEjrGI2"

API_URL = "https://dealer-backend-render.onrender.com"
GOOGLE_API_KEY = "AIzaSyD5MIjbpmSg673x_j3l_hJY2iZ39v3gFqI"

[theme]
base="dark"
primaryColor="#3B82F6"
backgroundColor="#0F172A"
secondaryBackgroundColor="#1E293B"
textColor="#E5E7EB"
font="sans serif"
